site_name: Prompt Engineering Class
site_description: 'Resources for teaching a class on prompt engineering. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/prompt-class'
repo_url: 'https://github.com/dmccreary/prompt-class'

nav:
  - Home: index.md
  - About: about.md
  - Sample Outline: sample-outline.md
  - Labs:
    - Intro: labs/index.md
    - Lists: labs/01-lists.md
    - License Lab: labs/01-license.md
    - Mermaid: labs/02-mermaid.md
    - Markdown Table: labs/03-markdown-table.md
    - Validate Zipcode: labs/04-validate-zipcode.md
    - Blue Circle: labs/05-p5-circle.md
    - Bouncing Ball: labs/05-bouncing-ball.md
    - Bouncing Ball Slider: labs/05-bouncing-ball-slider.md
    - Explain Embeddings: labs/06-explain-embeddings.md
    - Healthcare Costs: labs/07-healthcare-costs.md
    - Data Science Job Description: labs/08-job-description.md
    - Data Science Interview Questions: labs/09-interview-questions.md
    - Data Science Multiple Choice Quiz: labs/09-multiple-choice-quiz.md
    - GitHub Repo Analizer: labs/10-github-repo-analyzer.md
    - Plot Area of Continents: labs/11-plot-continents.md
    - Acceptance Test Plan: labs/12-acceptance-test-plan.md
    - Success Probability: labs/12-success-probability.md
    - Decomposition: labs/13-decomposition.md
    - Nell Image Prompt: labs/14-nell-image-prompt.md
    - Veiled-prime-prompt: labs/15-veiled-prime-prompt.md
    - Tutor: labs/16-tutor.md
    - Meta Prompts: labs/17-meta-prompts.md
    - KERNEL: labs/18-kernel.md`

  - Slides: slides.md
  - Instructor Notes: instructor-notes.md
  - Glossary: glossary.md
  - References: references.md
  - Contact: contact.md

# Dan's Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  extra_css:
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
copyright: Copyright &copy; 2025 Dan McCreary. Licensed under <a href="license/">CC BY-NC-SA 4.0</a> for non-commercial use.
extra:
  generator: false
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-NVZ3NEY8KG
